import { Download, FileSpreadsheet, FileText } from "lucide-react";
import { toast } from "sonner";
import { Panel } from "./Panel";
import { Button } from "@/components/ui/button";
import { missionsApi } from "@/api/missions";
import { useMission } from "@/hooks/useMission";

export function ExportPanel() {
  const { jobId, backendOnline } = useMission();

  const download = (kind: "csv" | "pdf") => {
    if (!backendOnline) {
      toast.error("Unable to connect to AEGIS backend.", {
        description: "-",
      });
      return;
    }
    window.open(missionsApi.exportUrl(jobId, kind), "_blank", "noopener");
    toast.success(`Preparing ${kind.toUpperCase()} export`, { description: `Job ${jobId}` });
  };

  return (
    <Panel title="Mission Exports" icon={<Download className="h-4 w-4" />}>
      <p className="text-xs text-muted-foreground">
        Reports are generated by the detection backend for job{" "}
        <span className="font-mono text-foreground">{jobId}</span>.
      </p>
      <div className="mt-3 flex flex-wrap gap-2">
        <Button onClick={() => download("csv")} className="gap-2">
          <FileSpreadsheet className="h-4 w-4" aria-hidden />
          Download Track CSV
        </Button>
        <Button variant="outline" onClick={() => download("pdf")} className="gap-2">
          <FileText className="h-4 w-4" aria-hidden />
          Download Mission PDF
        </Button>
      </div>
    </Panel>
  );
}
